### ISSUE TITLE
use php::global::php_version for php::repo::* version

### ISSUE THREAD

**Issue by mmoll** [voxpupuli/puppet-php#222]
...and further to build all URLs and further information needed, so that only `php::global::php_version` needs to get set and if `manage_repos` is true, the rest will happen automagically.

**Comment by gopalatvvs** [comment]
Hi
Today i configured mayflower/php - 3.4.1 through puppet. From yesterday onwards, ppa:ondrej/php5 throws dependencies errors. I changed my puppet script with ppa:ondrej/php and the php::global::php_version:  '5.5' in the yaml files. But it is not taking what am i specified repository ppa:ondrej/php and it is installed php5 and php7 also.

When am using cli, it shows 

PHP 7.0.12-1+deb.sury.org~trusty+1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.12-1+deb.sury.org~trusty+1, Copyright (c) 1999-2016, by Zend Technologies

Through Browser it shows "PHP 5.5.9-1ubuntu4.20 (cli) (built: Oct  3 2016 13:00:37) ".
 
I am getting following messages.

Notice: /Stage[main]/Php::Repo::Ubuntu/Apt::Ppa[ppa:ondrej/php5]/Exec[add-apt-repository-ppa:ondrej/php5]/returns: Cannot add PPA: 'ppa:ondrej/php5'.
Notice: /Stage[main]/Php::Repo::Ubuntu/Apt::Ppa[ppa:ondrej/php5]/Exec[add-apt-repository-ppa:ondrej/php5]/returns: Please check that the PPA name or format is correct.
Error: /usr/bin/add-apt-repository -y ppa:ondrej/php5 returned 1 instead of one of [0]
Error: /Stage[main]/Php::Repo::Ubuntu/Apt::Ppa[ppa:ondrej/php5]/Exec[add-apt-repository-ppa:ondrej/php5]/returns: change from notrun to 0 failed: /usr/bin/add-apt-repository -y ppa:ondrej/php5 returned 1 instead of one of [0]
Notice: /Stage[main]/Php::Repo::Ubuntu/Apt::Ppa[ppa:ondrej/php5]/File[/etc/apt/sources.list.d/ondrej-php5-trusty.list]: Dependency Exec[add-apt-repository-ppa:ondrej/php5] has failures: true
Warning: /Stage[main]/Php::Repo::Ubuntu/Apt::Ppa[ppa:ondrej/php5]/File[/etc/apt/sources.list.d/ondrej-php5-trusty.list]: Skipping because of failed dependencies

Warning: /Stage[main]/Apt::Update/Exec[apt_update]: Skipping because of failed dependencies


I have not specified any ondrej/php5 in my configuration. 

Please help to me in this case, it would be great.
