### ISSUE TITLE
ppa:ondrej/php5 does not exist

### ISSUE THREAD

**Issue by Conzar** [voxpupuli/puppet-php#270]
### Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 3.7.x
- Ruby:
- Distribution: Ubuntu 14.04
- Module version: 3.4.2

### How to reproduce (e.g Puppet code you use)
`
  class {'php':
    composer   => true,
    fpm            => false,
    pear          => true,
    phpunit     => true,
  }
`
### What are you seeing
apt-get cannot find the ppa because it no longer exists.

> W: Failed to fetch http://ppa.launchpad.net/ondrej/php5/ubuntu/dists/trusty/main/binary-amd64/Packages  404  Not Found
> W: Failed to fetch http://ppa.launchpad.net/ondrej/php5/ubuntu/dists/trusty/main/binary-i386/Packages  404  Not Found

### What behaviour did you expect instead
apt-get should complete without issue.

### Any additional information you'd like to impart
This is a show stopping bug for 3.4.2.

**Comment by pseudonamed** [comment]
I had this issue too. I fixed it by installing the module with an explicit version, in this case 4.0.0-beta1, as I don't think beta versions get installed by default. 

I believe this just became an issue now because [ppa:ondrej/php5](https://launchpad.net/~ondrej/+archive/ubuntu/ppa/php5) was just deprecated.

**Comment by juniorsysadmin** [comment]
@Conzar Is this still reproducible with the current version?

**Comment by Conzar** [comment]
@juniorsysadmin its not a problem for version 4.0.0-beta1.
