### ISSUE TITLE
Extension ini files missing priority in filename

### ISSUE THREAD

**Issue by JCotton1123** [voxpupuli/puppet-php#272]
Abandoning the issue template (sorry). I believe this affects all OS, versions of Puppet, versions of this module, and versions of php.

Each PHP extension will populate the php.d directly (/etc/php.d on RedHat) with one or more extension ini files. These ini files are prefixed with a number indicating a priority that causes them to be parsed in a specific order. The php::extension resource should be updated to include a "ini_priority" or similar parameter to mimic this behavior. This is a simple enough PR. However, I discovered this issue when I realized that the php.d directory was ending up with multiple ini setting files for each extension. Ex:

```
# ls /etc/php.d/
20-bz2.ini       20-dom.ini       20-gettext.ini         20-mysqlnd_mysql.ini  20-posix.ini      20-sqlite3.ini  20-tokenizer.ini  20-zip.ini          30-wddx.ini       odbc.ini
20-calendar.ini  20-exif.ini      20-iconv.ini           20-odbc.ini           20-shmop.ini      20-sysvmsg.ini  20-xml.ini        30-pdo_mysqlnd.ini  30-xmlreader.ini  pdo.ini
20-ctype.ini     20-fileinfo.ini  20-mysqlnd.ini         20-pdo.ini            20-simplexml.ini  20-sysvsem.ini  20-xmlwriter.ini  30-pdo_odbc.ini     40-json.ini       xml.ini
20-curl.ini      20-ftp.ini       20-mysqlnd_mysqli.ini  20-phar.ini           20-sockets.ini    20-sysvshm.ini  20-xsl.ini        30-pdo_sqlite.ini   mysql.ini
```

I am looking for suggestions on implementing the priority functionality and addressing the duplicate ini settings files issue in a user-friendly way. One option is to purge php.d but this is going to have unintended consequences. One option to place the burden on the user to make sure s/he sets the extension ini_priority (maybe with a default of 20 since most exts appear to have this prio) but this isn't really user friendly. We could create some kind of hash and lookup the default priority for each extension (again with a default of 20) but this is burdensome on us, the maintainers. Any thoughts?

**Comment by Vincent--** [comment]
Hi,

I don't have an answer for Redhat, but on Ubuntu, you can add the priority directly inside the ini file (in /etc/php/X.X/cli/mods-available/foo.ini):

```
foo => {
    settings       => {
        'extension' => 'foo.so',
        ';priority' => '25',
    },
    package_prefix => 'php-',
},

```

The important part is  `';priority' => '25',` (don't forget the `;` before priority)
And then phpenmod will create the link with the correct priority: `/etc/php/5.6/cli/conf.d/25-foo.ini` -> `/etc/php/X.X/cli/mods-available/foo.ini`

I have seen that in this module documentation, so hopefully this will help other people who might have an issue with the loading order of php extensions.

Regards,
Vincent.

**Comment by dbeckham** [comment]
I can confirm this behavior.  The comment is added, but it's also added again on each subsequent puppet run.  

A good use case for needing a  priority would be the pecl-couchbase extension.  In the current version, it requires the PHP json library be loaded.  But, because `(c)ouchbase` comes before `(j)son` in alphanumeric sort and all PHP modules are defined as priority 20 by default, the couchbase module is loaded first, causing it to fail.

### Example of the duplicated comments
```
extension = couchbase.so
;priority = 30
;priority = 30
```

**Comment by dbeckham** [comment]
I did some testing to see where the issue lies, and it looks like `ini_setting()` from [puppetlabs/puppetlabs-inifile](https://github.com/puppetlabs/puppetlabs-inifile) only supports comments in that it tries to ignore them.  Using `setting => '; priority', value => 'XX'` as a workaround is just taking advantage of the fact that the ini_setting function doesn't validate or reject settings that start with comment characters. Since it ignores comments when looking for matching setting, it just adds the same comments over and over again.

Given that Module priority in PHP is very important (opcache, pdo and xml must all be loaded very early),  and that the Ubuntu query, enmod and dismod tools use comments as a configuration method, the php::extension class can't treat these files as simple ini configs. It's not been a problem because it just happens to be that opcache, pdo and xml are installed by Apt on Ubuntu, and they manage their own configuration files, where pecl installed modules do not.

I think that from the help wanted tag on this issue, it's clear that this needs fixing, but I wanted to show my test config for whoever does end up fixing it.  I'll have to create a fix for our puppet config so that I can continue to use this module, but we aren't yet on Puppet 4, so my changes will be against the v4.0.0 tag. I have no way to use or test against any changes after that.

fwiw, here's my testing information:

## Versions:

foxpupuli/puppet-php: 4.0.0
puppetlabs-inifile: 1.6.0
Puppet: 3.8.x

## Example Puppet Code:

```puppet
ini_setting { 'test_inifile_1':
  ensure  => 'present',
  value   => 'bar',
  path    => '/tmp/test.ini',
  section => '',
  setting => 'foo',
}


ini_setting { 'test_inifile_2':
  ensure  => 'present',
  value   => '30',
  path    => '/tmp/test.ini',
  section => '',
  setting => '; priority',
}
```

## How to reproduce:

Run the above changes twice.  The first run will create a file with:

```
foo = bar
; priority = 30
```

The second run will modify the file to look like:

```
foo = bar
; priority = 30
; priority = 30
```

Every subsequent run after that will continue to add `;priority = 30` to the end of the file.

**Comment by jk2l** [comment]
Have you guys looked at this pull request? https://github.com/voxpupuli/puppet-php/pull/257

**Comment by jk2l** [comment]
Also want to add comment of my use case. We installed tideways-php, and it have a default priority of 40. Puppet generated give default priority of 20. so we can't override the priority with puppet unless we hardcode something outside of module (e.g. using fileline)

**Comment by Vincent--** [comment]
@jk2l , https://github.com/voxpupuli/puppet-php/pull/257 sounds good but it cannot be merge until conflicts are solved. Also this PR has been created 1 year ago and it hasn't been merged since. I suppose the "priority" management is not a priority for the maintainers 😁 
This PR might also need to manage priority changes: from what I understand after a quick look that will create the link with the correct priority but the previous link will still be present.

**Comment by jk2l** [comment]
@Vincent-- oh actually i created a new PR #335  but there is some discussion still need to be solve

**Comment by Vincent--** [comment]
Just seen that, thank you for that 😄 I've also asked the ppa maintainer if he can manage the priority directly with the script, see last comment here https://github.com/oerdnj/deb.sury.org/issues/575

**Comment by jk2l** [comment]
Yesterday in IRC discussed with @igalic and considering maybe we should not use phpquery instead we use puppet recursive and do full manage extensions via puppet?

@Vincent--

**Comment by jk2l** [comment]
One issue with phpenmod and phpdismod is that after you change the priority let say from 20 to 40

phpdismod can't detect 20-module.ini because it was looking at 40-module.ini
phpendmod will add a new 40-module.ini and now clean up any duplicate module.ini

if you are increase priority probably it is just override the priority of lower version, but decrease priority won't be able to work

**Comment by Vincent--** [comment]
I agree we have only 2 options here:
- use an optimised version of php*mod scripts to can fully the version
- or switch to puppet completely

About the "priority" change, this was the purpose of my comment in https://github.com/oerdnj/deb.sury.org/issues/575 : phpenmod should also remove existing links with other priority than the current one

**Comment by igalic** [comment]
i am in favour of using a puppet based solution… in a puppet module.
it gives us the chance of working on more platforms, simply by not spreading our energy too fin on accommodating all of their kinks.

**Comment by poikilotherm** [comment]
PR #333 seems to provide an easy solution to this...? At least it fixes @JCotton1123 initial request.

**Comment by poikilotherm** [comment]
Sorry for the noise - this missing feature actually leads to errors: as I installed `mysqlnd` via `php::extensions`, `mysqlnd.so` (non-prefixed file) gets loaded after `mysql.so`, `mysqli.so` and `pdo_mysql.so` (from prefixed files).

```
[root@web01 php.d]# ls -1 *mysql*.ini
30-mysqli.ini
30-mysql.ini
30-pdo_mysql.ini
mysqlnd.ini
```

This leads to mysql unavailable within PHP:
```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/mysql.so' - /usr/lib64/php/modules/mysql.so: undefined symbol: mysqlnd_connect in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/mysqli.so' - /usr/lib64/php/modules/mysqli.so: undefined symbol: mysqlnd_connect in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/pdo_mysql.so' - /usr/lib64/php/modules/pdo_mysql.so: undefined symbol: mysqlnd_allocator in Unknown on line 0
```

Environment: CentOS 7, PHP 5.6 from IUS, voxpopuli/puppet 4.0.0.

**Comment by poikilotherm** [comment]
Sorry guys for disturbing again... This issue is kind of a blocker and there seems to be a simple solution presented in #333. Could you give it a shoot, fix this ASAP and maybe push a bugfix release to the forge? Thanks for your great work!

**Comment by jmk61** [comment]
Bumping this again...This issue really needs to be fixed!

**Comment by luisbrandao** [comment]
This STILL is an issue for me.

**Comment by alexwiedermann** [comment]
Me too

**Comment by poikilotherm** [comment]
@JCotton1123 is your particular problem solved with #333 being merged so this might be closed?

**Comment by JCotton1123** [comment]
@poikilotherm yes, #333 resolves my original issue. I'll close this. For others, I guess create a new issue with a better description if you're still facing an issue.

**Comment by minorOffense** [comment]
What we probably want to avoid having to manually set the priorities manually is some kind of conf dir purge. And then make sure the module defines the default conf files properly. Then any files created by package managers are removed in favour of the puppet ones. 

Just a thought.
