### ISSUE TITLE
Unused variable 'log_group_final'

### ISSUE THREAD

**Issue by paescuj** [voxpupuli/puppet-php#568]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: irrelevant
- Ruby: irrelevant
- Distribution: irrelevant
- Module version: v7.0.0

## How to reproduce (e.g Puppet code you use)

irrelevant

## What are you seeing

The variable 'log_group_final', defined in [fpm/config.pp](https://github.com/voxpupuli/puppet-php/blob/v7.0.0/manifests/fpm/config.pp#L100-L104), is not used anywhere.

```
~/puppet-php $ grep log_group_final -r
docs/puppet_classes/php_3A_3Afpm_3A_3Aconfig.html:  $log_group_final = $log_group ? {
manifests/fpm/config.pp:  $log_group_final = $log_group ? {
```

## What behaviour did you expect instead

The variable assignment should be removed.

**Comment by rwaffen** [comment]
i have something to add... also `log_owner` is never used. we had the desire to do so, but than saw that it is complete ignored...

**Comment by paescuj** [comment]
@rwaffen Did you want to set the owner of the directory /var/log/php-fpm? If you want to do so, I could update my pull request #570 accordingly.

**Comment by fbrehm** [comment]
To leave my 50 cent: the expected behavior should be also to set the owner of all log files below /var/log/php-fpm. We are coming in big trouble with logrotate if the owner of the directory is e.g. apache, and the owner of the logfiles is root.
But to be honest, I don't know whether there is a way to define tho ownership of the log files in the PHP FPM configuration.
